# PR auto-labeling rules — used by .github/workflows/labeler.yml
# Maps file path globs to labels applied automatically on PRs.

spec:
  - changed-files:
      - any-glob-to-any-file: "specs/**"

task:
  - changed-files:
      - any-glob-to-any-file: "tasks/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
          - "!specs/**"
          - "!tasks/**"

agent:
  - changed-files:
      - any-glob-to-any-file: ".github/agents/**"

skill:
  - changed-files:
      - any-glob-to-any-file: ".github/skills/**"

app:
  - changed-files:
      - any-glob-to-any-file: "app/**"

scripts:
  - changed-files:
      - any-glob-to-any-file:
          - "scripts/**"
          - "run.sh"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "pyproject.toml"
          - "uv.lock"
          - "requirements*.txt"
          - ".pre-commit-config.yaml"
