name: Task
description: Create a specific implementation task
title: "[TASK]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Create an Implementation Task
        Break down a spec into a specific, actionable task.
        
  - type: input
    id: spec-id
    attributes:
      label: Related Spec ID
      description: Which spec does this task implement?
      placeholder: "SPEC-001"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: "Implement the user authentication endpoint"
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Endpoint responds to POST /auth/login
        - [ ] Returns JWT token on success
        - [ ] Returns 401 on invalid credentials
    validations:
      required: true
      
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How long will this take?
      options:
        - Small (< 2 hours)
        - Medium (2-8 hours)
        - Large (> 8 hours)
    validations:
      required: true
      
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What must be completed before this task?
      placeholder: "TASK-001-1, TASK-001-2"
      
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any implementation details or approaches to consider
